authors = ["Mehmet Hakan Satman (jbytecode) <mhsatman@gmail.com>"]
name = "JMCDM"
uuid = "358108f5-d052-4d0a-8344-d5384e00c0e5"
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
